# Generated by Django 2.0 on 2018-02-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180207_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internalID', models.IntegerField()),
                ('orderCreationTime', models.DateTimeField()),
                ('merchantID', models.IntegerField()),
                ('status', models.CharField(max_length=120)),
                ('amount', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=120)),
                ('orderID', models.IntegerField()),
                ('orderType', models.CharField(max_length=120)),
                ('orderDescription', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
