# Generated by Django 2.0 on 2018-02-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180211_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='internalID',
            field=models.IntegerField(),
        ),
    ]
